import { ExperienceListProps } from "../components/experience/ExperienceList";

export const EXPERIENCE_DATA: ExperienceListProps[] = [
  {
    company: "Jobandtalent",
    rol: "Frontend Developer",
    period: "Dec. 2021 - May. 2024",
    location: "Remote",
    description: [
      "Development of web applications in Retool using JavaScript.",
      "Development of web applications using React, TypeScript, and Next.",
      "Validation schemes using Yup and Zod.",
      "Testing with React Testing Library and Jest.",
      "Using APIs and Google Sheets as databases.",
      "Version control using Git and Github.",
    ],
    skills: [
      "Typescript",
      "React",
      "Css",
      "Tailwind",
      "Yup",
      "Zod",
      "Jest",
      "Next",
      "Microfrontend",
      "Git",
      "Github",
      "Retool",
    ],
    projects: [],
  },
  {
    company: "Entain - Bwin, Sportingbet & Betboo",
    rol: "UI & Web Designer",
    period: "abr. 2019 - ago. 2021",
    location: "Barcelona, Catalonia, Spain",
    description: [
      "Design for advertising campains and for web and social media promotions.",
      "Email design and layout.",
      "Video edition.",
    ],
    skills: ["Photoshop", "Illustrator", "AfterEfects", "Html", "Css", "Git"],
    projects: [],
  },
  {
    company: "Rucker Lypsa - SEAT",
    rol: "UI/UX Designer | HMI Concept | SEAT Infotainment",
    period: "oct. 2017 - abr. 2019",
    location: "Martorell, Catalonia, Spain",
    description: [
      "Concept, design and graphic specification of the main radio screens for SEAT vehicles.",
      "User test.",
    ],
    skills: ["UX/UI", "Photoshop"],
    projects: [],
  },
  {
    company: "Dinamic Comunicacio",
    rol: "Web designer and Layout",
    period: "ene. 2016 - jul. 2017",
    location: "Barcelona, Catalonia, Spain",
    description: [
      "Design for advertising campains and for web and social media promotions.",
      "Product photography.",
      "Photography and video edition.",
      "Design, layout and personalisation of landing pages, email campains, websites and apps.",
      "Multiclient project management.",
    ],
    skills: [
      "Photoshop",
      "Illustrator",
      "Indesign",
      "AfeterEfects",
      "Joombla",
      "Wordpress",
      "Html",
      "Css",
    ],
    projects: [],
  },
  {
    company: "Birrabox",
    rol: "Graphic designer, freelance",
    period: "jun. 2015 - may. 2016",
    location: "Barcelona, Catalonia, Spain",
    description: [
      "Advertisement banner design for web and social media.",
      "Photographic edition.",
      "Product design and finals arts for printing.",
      "Landing and web design and layout.",
    ],
    skills: ["Photoshop", "Illustrator"],
    projects: [],
  },
  {
    company: "Groupalia",
    rol: "Graphic designer",
    period: "jul. 2015 - dic. 2015",
    location: "Barcelona, Catalonia, Spain",
    description: [
      "Photographic selection and retouching.",
      "Banner web design.",
    ],
    skills: ["Photoshop", "Illustrator"],
    projects: [],
  },
  {
    company: "Offerum",
    rol: "Graphic designer",
    period: "nov. 2014 - jun. 2015",
    location: "Barcelona, Catalonia, Spain",
    description: ["Photographic selection and retouching."],
    skills: ["Photoshop"],
    projects: [],
  },
];
