export const PROJECTS_DATA = [
  {
    header: "Bootcamp Project - 2021",
    title: "Title project",
    description:
      "Project description, Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sed nunc at magna lacinia ultrices. Ut interdum ac enim vel aliquam .",
    skills: [
      "Javascript",
      "Javascript",
      "Javascript",
      "Javascript",
      "Javascript",
      "Javascript",
    ],
    imageSrc: "../../public/hungry_cats.jpg",
    githubLink: "https://github.com/lauraAlabau/proyect-1_the-game",
    previewLink: "https://lauraalabau.github.io/proyect-1_the-game/index.html",
    otherLink: "",
  },
  {
    header: "Bootcamp Project - 2021",
    title: "Title project 2",
    description:
      "Project description, Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sed nunc at magna lacinia ultrices. Ut interdum ac enim vel aliquam .",
    skills: [
      "Typescript",
      "Typescript",
      "Typescript",
      "Typescript",
      "Typescript",
      "Typescript",
    ],
    imageSrc: "../../public/pro_imgs/hungry_cats.jpg",
    githubLink: "https://github.com/lauraAlabau/proyect-1_the-game",
    previewLink: "https://lauraalabau.github.io/proyect-1_the-game/index.html",
    otherLink: "",
  },
  {
    header: "Bootcamp Project - 2021",
    title: "Title project 2",
    description:
      "Project description, Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sed nunc at magna lacinia ultrices. Ut interdum ac enim vel aliquam .",
    skills: [
      "Typescript",
      "Typescript",
      "Typescript",
      "Typescript",
      "Typescript",
      "Typescript",
    ],
    imageSrc: "../../public/pro_imgs/hungry_cats.jpg",
    githubLink: "https://github.com/lauraAlabau/proyect-1_the-game",
    previewLink: "https://lauraalabau.github.io/proyect-1_the-game/index.html",
    otherLink: "",
  },
  {
    header: "Bootcamp Project - 2021",
    title: "Title project 2",
    description:
      "Project description, Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sed nunc at magna lacinia ultrices. Ut interdum ac enim vel aliquam .",
    skills: [
      "Typescript",
      "Typescript",
      "Typescript",
      "Typescript",
      "Typescript",
      "Typescript",
    ],
    imageSrc: "../../public/hungry_cats.jpg",
    githubLink: "https://github.com/lauraAlabau/proyect-1_the-game",
    previewLink: "https://lauraalabau.github.io/proyect-1_the-game/index.html",
    otherLink: "",
  },
  {
    header: "Bootcamp Project - 2021",
    title: "Title project 2",
    description:
      "Project description, Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sed nunc at magna lacinia ultrices. Ut interdum ac enim vel aliquam .",
    skills: [
      "Typescript",
      "Typescript",
      "Typescript",
      "Typescript",
      "Typescript",
      "Typescript",
    ],
    imageSrc: "../../public/pro_imgs/hungry_cats.jpg",
    githubLink: "https://github.com/lauraAlabau/proyect-1_the-game",
    previewLink: "https://lauraalabau.github.io/proyect-1_the-game/index.html",
    otherLink: "",
  },
  {
    header: "Bootcamp Project - 2021",
    title: "Title project 2",
    description:
      "Project description, Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sed nunc at magna lacinia ultrices. Ut interdum ac enim vel aliquam .",
    skills: [
      "Typescript",
      "Typescript",
      "Typescript",
      "Typescript",
      "Typescript",
      "Typescript",
    ],
    imageSrc: "../../public/pro_imgs/hungry_cats.jpg",
    githubLink: "https://github.com/lauraAlabau/proyect-1_the-game",
    previewLink: "https://lauraalabau.github.io/proyect-1_the-game/index.html",
    otherLink: "",
  },
];
